model: "tic_hp"
dataset: "imagenet"
dataset_path: '/work/dataset/ILSVRC'
epochs: 400
learning_rate: 1.e-4
num_workers: 8
quality_level: 4 # {1,2,3,4}
lmbda:  0.013 # {0.0018, 0.0035, 0.0067, 0.013}
batch_size: 10
test_batch_size: 8
aux_learning_rate: 1.e-3
patch_size: 224
cuda: True
gpu_id: 0
save: True
clip_max_norm: 1.0
name: "TransTIC_WhiteVIP"
exp_name: "TransTIC_WhiteVIP"
root: "/work/TransTICB"
seed: 42
checkpoint: "/work/TransTICB/weights/base_codec_4.pth.tar"  # could be pre-trained base codec (for training) or trained TransTIC (for evaluation)
restore: 'scratch'
prompt_config: 
TRANSFER_TYPE: "BlackVIP"
VPT_lmbda: 0.0018

BLACKVIP:
  METHOD: "coordinator"
  PT_BACKBONE: 'vit-mae-base'
  SRC_DIM: 1568
  E_OUT_DIM: 0
  SPSA_PARAMS: [1.0, 0.01, 0.01, 0.4, 0.1]
  OPT_TYPE: "spsa-gc"
  MOMS: 0.9
  SP_AVG: 5
  P_EPS: 1.0
